Add a type annotation to generated code to allow type inference to work.
autometrics-dev/autometrics-rs pull request #74
Opened 2023-04-25 17:08 UTC by adeschamps

Since the generated code wraps the original function body in an expression of the form
`let return = { /* original function body /* };`, this can cause type inference to not work on
return expressions like the following:

```rust
#[autometrics]
fn foo() -> Vec<usize> {
    (0..10).collect()
}
```

This patch puts the function's return type as an explicit type annotation on the `let return =` in
the generated code.

2023-04-26 07:52 UTC, emschwartz requested changes
Thanks @adeschamps for the PR! And good catch about this issue 😊 

Could you add a couple of tests to make sure that this works with various types of return values? The one that sticks out is the `impl Trait` but I wonder if there are any other cases that might cause problems.

2023-04-26 07:52 UTC, emschwartz commented on autometrics/src/lib.rs
> +///        # (0..10).collect()
I'd prefer to have this as a test instead of in the example

2023-04-26 08:42 UTC, gagbo commented
> Could you add a couple of tests to make sure that this works with various types of return values? The one that sticks out is the `impl Trait` but I wonder if there are any other cases that might cause problems.

Maybe we could try to be done with https://github.com/autometrics-dev/autometrics-rs/pull/61 (I can edit the `ErrorLabels` macro to mark it as unstable if need be), so that `trybuild` is added to the project and we can add a bunch of compile tests using the macro to create cases where it is invoked with anonymous types like that

2023-04-30 14:23 UTC, adeschamps commented
Ah yes, I didn't consider `impl Trait`. Good catch. I thought about this a bit, and I think the trick is that rather than just inlining the body of the function, we can define an internal function with the same signature. Something like this:

```rust
fn foo() -> ReturnType {
    // original function
    fn __internal_foo() -> ReturnType {
        // ...
    }
    /* header */
    let result = __internal_foo(args...);
    /* footer */
    result
}
```

I'll experiment with this.

2023-05-01 08:18 UTC, emschwartz commented
@adeschamps it might also be worth looking at how the `tracing::instrument` macro handles this type of case. It does similar rewriting logic but covers a lot more edge cases

2023-05-03 12:26 UTC, gagbo commented
Actually I had to bring parts of the changes to make a feature in #61 to work. I dodged the anonymous type issue by simply not emitting any code for this specific case

2023-05-09 15:09 UTC, closed without merging